import { useMeetingStore } from './store.js'
import { useState } from 'react'

export default function ExportSummary() {
  // ✅ FIX: Subscribe to state changes properly
  const meetingState = useMeetingStore(state => state.meetingState)
  const { actions, decisions, parking_lot, participation } = meetingState
  
  const [copied, setCopied] = useState(false)
  
  const generateSummary = () => {
    const timestamp = new Date().toLocaleString()
    
    let summary = `📋 MEETING SUMMARY\n`
    summary += `Generated: ${timestamp}\n`
    summary += `\n`
    summary += `${'='.repeat(50)}\n\n`
    
    // Action Items
    summary += `📌 ACTION ITEMS (${actions.length})\n`
    summary += `${'-'.repeat(50)}\n`
    if (actions.length > 0) {
      actions.forEach((action, i) => {
        summary += `${i + 1}. ${action.speaker} will ${action.task}\n`
        summary += `   ⏰ Deadline: ${action.deadline}\n`
        summary += `   ✨ Confidence: ${Math.round(action.confidence * 100)}%\n\n`
      })
    } else {
      summary += `No action items.\n\n`
    }
    
    // Decisions
    summary += `\n💡 DECISIONS MADE (${decisions.length})\n`
    summary += `${'-'.repeat(50)}\n`
    if (decisions.length > 0) {
      decisions.forEach((decision, i) => {
        const decisionText = typeof decision === 'string' ? decision : decision.what || decision
        summary += `${i + 1}. ${decisionText}\n`
      })
    } else {
      summary += `No decisions made.\n`
    }
    
    // Parking Lot
    summary += `\n\n🅿️ PARKING LOT (${parking_lot.length})\n`
    summary += `${'-'.repeat(50)}\n`
    if (parking_lot.length > 0) {
      parking_lot.forEach((item, i) => {
        summary += `${i + 1}. ${item}\n`
      })
    } else {
      summary += `No items parked.\n`
    }
    
    // Participation
    summary += `\n\n👥 PARTICIPATION\n`
    summary += `${'-'.repeat(50)}\n`
    const participants = Object.entries(participation)
    if (participants.length > 0) {
      participants.forEach(([name, stats]) => {
        summary += `• ${name}: ${stats.turns} contribution${stats.turns !== 1 ? 's' : ''}\n`
      })
    } else {
      summary += `No participation data.\n`
    }
    
    summary += `\n${'='.repeat(50)}\n`
    summary += `\nGenerated by Sarah AI Meeting Facilitator 🤖\n`
    
    return summary
  }
  
  const copyToClipboard = async () => {
    try {
      const summary = generateSummary()
      await navigator.clipboard.writeText(summary)
      setCopied(true)
      console.log('✅ Summary copied to clipboard')
      
      // Reset after 2 seconds
      setTimeout(() => setCopied(false), 2000)
    } catch (error) {
      console.error('❌ Copy failed:', error)
      alert('Failed to copy. Please try again.')
    }
  }
  
  const downloadSummary = () => {
    const summary = generateSummary()
    const blob = new Blob([summary], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `meeting-summary-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    console.log('✅ Summary downloaded')
  }
  
  const hasContent = actions.length > 0 || decisions.length > 0 || parking_lot.length > 0
  
  return (
    <div className="bg-white/10 backdrop-blur-lg p-6 rounded-2xl border border-white/20 shadow-2xl">
      <h3 className="font-semibold text-lg mb-4 text-white">
        📄 Export Summary
      </h3>
      
      {hasContent ? (
        <div className="space-y-3">
          {/* Copy Button */}
          <button
            onClick={copyToClipboard}
            className={`w-full py-3 rounded-xl font-semibold transition-all ${
              copied 
                ? 'bg-green-500 text-white' 
                : 'bg-blue-500 hover:bg-blue-600 text-white'
            }`}
          >
            {copied ? '✅ Copied!' : '📋 Copy to Clipboard'}
          </button>
          
          {/* Download Button */}
          <button
            onClick={downloadSummary}
            className="w-full py-3 bg-purple-500 hover:bg-purple-600 text-white rounded-xl font-semibold transition-all"
          >
            💾 Download as File
          </button>
          
          {/* Preview */}
          <div className="mt-4 p-3 bg-white/5 rounded-xl border border-white/10">
            <div className="text-xs text-white/60 mb-2">Preview:</div>
            <div className="text-xs text-white/80 font-mono whitespace-pre-wrap max-h-40 overflow-y-auto">
              {generateSummary().split('\n').slice(0, 10).join('\n')}
              {generateSummary().split('\n').length > 10 && '\n...'}
            </div>
          </div>
          
          {/* Stats */}
          <div className="flex gap-2 text-xs">
            <span className="px-2 py-1 bg-green-500/20 text-green-300 rounded">
              {actions.length} action{actions.length !== 1 ? 's' : ''}
            </span>
            <span className="px-2 py-1 bg-yellow-500/20 text-yellow-300 rounded">
              {decisions.length} decision{decisions.length !== 1 ? 's' : ''}
            </span>
            <span className="px-2 py-1 bg-red-500/20 text-red-300 rounded">
              {parking_lot.length} parked
            </span>
          </div>
        </div>
      ) : (
        <div className="text-white/40 text-center py-8 text-sm">
          No content to export yet.<br/>
          Start a meeting to generate a summary!
        </div>
      )}
    </div>
  )
}